### ISSUE TITLE
Quisiera que esto estuviera escrito en Go!

### ISSUE THREAD

**Issue by mogox** [alan-andrade/embeddable-chats#1]

**Comment by mogox** [comment]
This is not very helpful and fails over an over.  This is a test for http://railsrumble.com/

**Comment by alan-andrade** [comment]
I appreciate your concern for this repo. I'm very happy to know people like you take the time to file bug tickets.

I will take a look  :)  Have a great rails rumble weekend.

**Comment by mogox** [comment]
I'm very sad about this.  This is NOT working. :-1: :cry:

**Comment by alan-andrade** [comment]
This is the worst comment I'll ever do just to make the karma requests index to go down. This sucks! We need to tell people the index varies depending on how many comments you have on your repo. :( 

Anyways, rails rumble was awesome.

**Comment by alan-andrade** [comment]
bad wrong! assault stupid fucker idiot!

**Comment by alan-andrade** [comment]
Abandoned
Abrasive
Abrupt
Abused
Abusive
Accused
Addicted
Afraid
Aggravated
Aggressive
Alone
Aloof
Ambiguous
Angry
Anguish
Annoyed
Anxious
Apprehensive
Argumentative
Arrogant
Artificial
Ashamed
Assaulted
At a loss
At risk
Atrocious
Attacked
Avoided

**Comment by alan-andrade** [comment]
Bad
Badgered
Baffled
Banned
Barren
Beat
Beaten down
Belittled
Belligerent
Berated
Betrayed
Bewildered
Bitched at
Bitter
Bizzare
Blacklisted
Blackmailed
Blamed
Bleak
Blown away
Blur
Boorish

**Comment by alan-andrade** [comment]
Crabby
Cramped
Cranky
Crap
Crappy
Crazy
Creeped out
Creepy
Critical
Criticized
Cross
Crowded
Cruddy
Cruel
Crummy
Crushed
Cut-down
Cut-off
Cynical
Damaged
Damned
Dangerous

**Comment by mogox** [comment]
:-1: bu! Bad behavior!

**Comment by alan-andrade** [comment]
I know, I'm an asshole. And the guys from the rails rumble want to kick me out from the developers community. Shit! I need to get my shit toghether man !

Arrrgggghhhh! I can't! NO NO NO
