### ISSUE TITLE
Negativity all around!

### ISSUE THREAD

**Issue by mogox** [alan-andrade/embeddable-chats#2]

**Comment by mogox** [comment]
No, no no and no! This is just wrong

**Comment by alan-andrade** [comment]
fuck this thing, I quit. Fuck open source, I'm going to rewrite my own microsfot windows.

**Comment by alan-andrade** [comment]
``` ruby
100.times do
   hate @mogox
end
```

Yeah, that's right. haha

**Comment by alan-andrade** [comment]
argh.

**Comment by alan-andrade** [comment]
boo !  this code should evaluate on real life!

**Comment by alan-andrade** [comment]
Hey look! I have some bad words for you mother %$#^

Dirty
Disabled
Disagreeable
Disappointed
Disappointing
Disapproved of
Disarray
Disbelieved
Discardable
Discarded

**Comment by mogox** [comment]
what's up dude?  Won't make it happen!

**Comment by alan-andrade** [comment]
:dizzy_face:

**Comment by alan-andrade** [comment]
you go :disappointed:
